### ISSUE TITLE
[Bug] Loss may differ from num() dimension

### ISSUE THREAD

**Issue by HolmesShuan** [yihui-he/caffe-dice-loss-layer#1]
I think, differ from ||x-y||^2 loss , dice loss should be calculated **Bottom[i]->num()** times separately. ||x-y||^2 is just an exception whose derivative could be expanded. [Here](https://github.com/HolmesShuan/Dice-coefficient-Loss-Caffe-Layer) is my personal Caffe reimplementation to fully explain my opinion.

**Comment by ethanhe42** [comment]
Just a reimplement my Keras code: https://github.com/yihui-he/u-net/blob/master/train.py#L22
